
/**
 * 
 * autogenerated by solidity-visual-auditor
 * 
 * execute with: 
 *  #> truffle test <path/to/this/test.js>
 * 
 * */
var MockERC20Hook = artifacts.require("/home/et3p0/projects/q-contracts/contracts/mocks/ERC20Hook/ERC20Hook.sol");

contract('MockERC20Hook', (accounts) => {
    var creatorAddress = accounts[0];
    var firstOwnerAddress = accounts[1];
    var secondOwnerAddress = accounts[2];
    var externalAddress = accounts[3];
    var unprivilegedAddress = accounts[4]
    /* create named accounts for contract roles */

    before(async () => {
        /* before tests */
    })

    beforeEach(async () => {
        /* before each context */
    })

    it('should revert if ...', () => {
        return MockERC20Hook.deployed()
            .then(instance => {
                return instance.publicOrExternalContractMethod(argument1, argument2, { from: externalAddress });
            })
            .then(result => {
                assert.fail();
            })
            .catch(error => {
                assert.notEqual(error.message, "assert.fail()", "Reason ...");
            });
    });

    context('testgroup - security tests - description...', () => {
        //deploy a new contract
        before(async () => {
            /* before tests */
            const newMockERC20Hook = await MockERC20Hook.new()
        })


        beforeEach(async () => {
            /* before each tests */
        })



        it('fails on initialize ...', async () => {
            return assertRevert(async () => {
                await newMockERC20Hook.initialize()
            })
        })

        it('checks if method returns true', async () => {
            assert.isTrue(await newMockERC20Hook.thisMethodShouldReturnTrue())
        })
    })
});
